### ISSUE TITLE
quad.Expr() adds new line at the end

### ISSUE THREAD

**Issue by linediconsine** [SeanJxie/polygo#1]
I noted that quad.Expr() adds a newline \n at the end of the strings 

Expected 

"0.000000x^0 + 0.000000x^1 + 2.000000x^2" 

Actual results

"0.000000x^0 + 0.000000x^1 + 2.000000x^2
"

The quote in the actual result ending in a new line, I would expect the first ( I consider this as a stringify ),

 or am I missing something?

**Comment by SeanJxie** [comment]
Thanks for the feedback! I will change this in the next patch. If you would like, you may even make the change through a PR :)
