### ISSUE TITLE
References for algorithms used and example of usage

### ISSUE THREAD

**Issue by linediconsine** [SeanJxie/polygo#7]
Hi, SanJxie

I would love some more examples of usage of this library, in particular, I am curious about how FFT works.
About FFT I would also like to understand the implementation, I know the main concept but see a reference of why we implemented it in that way could be interesting.

Just sharing some idea here ;)

**Comment by SeanJxie** [comment]
Hi,

I referenced [this paper](http://www.cs.toronto.edu/~denisp/csc373/docs/tutorial3-adv-writeup.pdf) when implementing the FFT functions. There are also many nice online resources to find implementations and examples, many of which are quite similar. [Here's](https://medium.com/@aiswaryamathur/understanding-fast-fourier-transform-from-scratch-to-solve-polynomial-multiplication-8018d511162f) an example.

Have a great day,
Sean Xie
