### ISSUE TITLE
FindRootsWithin not always returning correct results

### ISSUE THREAD

**Issue by MartinSimangoDaemn** [SeanJxie/polygo#8]
Hi @SeanJxie 

I found that FindRootsWithin doesn't always return the correct roots. 

Here is an example of a polynomial i used:
x^21 - 86400x +86399=0

1. When I used FindRootsWithin(1,100) I get the following roots: [14.912790 1.000000] : (14.912790 is not a valid root)
2. When I used FindRootsWithin(0,100) I got the following roots: [1.000000 1.687851] - which are correct.
3. When I used FindRootsWithin(-100,100) I got the following roots: [-14.765139 1.000000 1.687851] of which -14.765139  is not a valid root.

**Comment by SeanJxie** [comment]
Hello @MartinSimangoDaemn 

Thank you for pointing this bug out. It has been fixed as a result of the Polygo rewrite.

```go
p := NewPolyFromString("x^21 - 86400x + 86399")
s := NewSolverDefault()

fmt.Println(s.FindRootsWithin(p, 1, 100))
fmt.Println(s.FindRootsWithin(p, 0, 100))
fmt.Println(s.FindRootsWithin(p, -100, 100))
```
Now, you can also find all roots at once:
```go
fmt.Println(s.FindRoots(p))
```
Cheers,
Sean
